
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaycwyrtkkzltzmwubja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlheWN3eXJ0a2t6bHR6bXd1YmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NTU0OTUsImV4cCI6MjA2MTEzMTQ5NX0.Wp-xgFZwsoSQral_MDAw6INjwu-HuQarzKlkgOUijEY";
const OPENAI_API_KEY = "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";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export { OPENAI_API_KEY };
